### ISSUE TITLE
Environmental variable _SessionHostParameters values DomainJoinUserName and ADOUPath do not correspond with template spec

### ISSUE THREAD

**Issue by Rai80** [Azure/AVDSessionHostReplacer#10]
In the template spec the variables are:

.OUPath vs ADOUPath
.UserName vs DomainJoinUsername

**Comment by WillyMoselhy** [comment]
Fixed in [v.0.2.8](https://github.com/Azure/AVDSessionHostReplacer/releases/tag/v0.2.8)
