### ISSUE TITLE
Targetsessionhostcount & allowdownsizing not working

### ISSUE THREAD

**Issue by ankurvvvv** [Azure/AVDSessionHostReplacer#12]
I have set the "targetsessionhostcount" to 15 and "allowdownsizing" true but the funtion keeps on creating the sessionhost.
I manually have to stop the function.

**Comment by ankurvvvv** [comment]
Turned out the function started creating sessionhost from correct latest version of the image but ended up creating sessionhosts from old version of the image, resulted function created more then target sessionhost defined and keeps growing. I have delete the old image inorder to correct this operation. 

Reference invocation logs provided over Teams.

<img width="379" alt="image" src="https://github.com/user-attachments/assets/4f62a588-6a34-4ec4-8ae0-1be36e05531e">

**Comment by WillyMoselhy** [comment]
Fixed in [v0.2.8](https://github.com/Azure/AVDSessionHostReplacer/releases/tag/v0.2.8)
