### ISSUE TITLE
Error when deploying via the UI

### ISSUE THREAD

**Issue by thor-m** [Azure/AVDSessionHostReplacer#24]
When I am attempting to deploy AvdSessionHostReplacer to a host pool using the UI option, I get the following error: `Deployment template validation failed: 'The template resource 'deployFunctionApp' at line '389' and column '5' is not valid: The language expression property array index '2' is out of bounds.. Please see https://aka.ms/arm-functions for usage details.'. (Code: InvalidTemplate)`

**Comment by WillyMoselhy** [comment]
Hi @thor-m , can you share more details on what options you selected? you can ping me on Teams wmoselhy[at]microsoft.com

**Comment by thor-m** [comment]
@WillyMoselhy  Thanks, I have sent you a screenshot of my inputs and parameters over Teams

**Comment by WillyMoselhy** [comment]
This is a regression in the latest update when choosing and MSI. I am working on a fix and will release it ASAP.

**Comment by jwaltireland** [comment]
Getting similar error when running the DeployAVDSessionHostReplacer.bicep:   

New-AzResourceGroupDeployment: /home/runner/work/avdsessionhostreplacer-nih/avdsessionhostreplacer-nih/.github/workflows/scripts/Deploy-To-Test.ps1:94
Line |
  94 |  New-AzResourceGroupDeployment @paramNewAzResourceGroupDeployment
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | 14:36:07 - Error: Code=InvalidTemplate; Message=Deployment template
     | validation failed: 'The template resource 'deployFunctionApp' at line
     | '6' and column '9' is not valid: The language expression property array
     | index '2' is out of bounds.. Please see https://aka.ms/arm-functions for
     | usage details.'.

**Comment by WillyMoselhy** [comment]
@jwaltireland , I am digging into it :)

**Comment by jwaltireland** [comment]
i ran the cmd line/bicep using the : 

TemplateUri = 'https://raw.githubusercontent.com/Azure/AVDSessionHostReplacer/v0.3.1-beta.1/deploy/arm/DeployAVDSessionHostReplacer.json'

and it deployed successfully.

**Comment by thor-m** [comment]
Template validation was successful during the UI deployment. The resource deployment was successful when I enabled logging and specified a Log Analytics workspace.

When I tried to deploy without logging enabled, I received an error in regards to the deployment of the Function App. The dependent App Insights resource did not exist. Not sure if this piece needs to be there if no logging is desired.
