### ISSUE TITLE
Deploy more than 1 host per hour

### ISSUE THREAD

**Issue by jobasque** [Azure/AVDSessionHostReplacer#7]
I saw a parameter in the function app (FunctionApp/FunctionParameters.psd1) that shows as follows:

_MaxSimultaneousDeployments                   = @{Required = $false ; Type = 'int   '  ; Default = 100; 
Description = 'Deprecated.This allows multiple deployments running simultaneously. Might change later to control maximum number of VMNames to deploy. Or control it using batches in template, or both!.' }

How can we modify the function app to control number of session hosts created each run? I currently see only 1 new session host created per hour. I would like to increase this number to support deployment of many more than 24 session hosts per day.

**Comment by WillyMoselhy** [comment]
The default will allow it to deploy multiple VMs at a time, assuming that multiple VMs are needed. I am happy to discuss this on Teams, I see you found me 👯

**Comment by jpplaisier** [comment]
I have the same question. Can you share the solution if available here? In my case (bicep deployment of Session Host Replacer) the tool also deploys one host every hour.

**Comment by jobasque** [comment]
> I have the same question. Can you share the solution if available here? In my case (bicep deployment of Session Host Replacer) the tool also deploys one host every hour.

Jpplaisier -- Check the branch: dev-removemaxDeploymentCount 
https://github.com/Azure/AVDSessionHostReplacer/compare/Dev-RemoveMaxDeploymentCount

Willy made some progress on this today and it looked good in testing. Here are the list of commits for it today:

https://github.com/Azure/AVDSessionHostReplacer/commits/Dev-RemoveMaxDeploymentCount
