### ISSUE TITLE
Deploy mutiple function apps simultaneously

### ISSUE THREAD

**Issue by jobasque** [Azure/AVDSessionHostReplacer#8]
How can we deploy more than 1 function app at a time? In the portal-ui template, I did not see an option to customize the name of the function app nor to allow it to ignore other function apps in the subscription, so that mutiple function apps can be used to manage separate batches of session hosts. When I deployed a new function app, it appears to have taken over the previously created function app, modifying its settings. 

Thank you.

**Comment by WillyMoselhy** [comment]
The name of the function app is intentionally not customizable as it is calculated to be a unique value in the Portal-UI. You can customize the bicep deployment to provide a custom name. Remember that he Session Host Replacer is designed to manage one host pool. So you cannot have more than one per pool. If your goal is to batch upgrade, I recommend doing this using the [batch() function in bicep](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/loops#deploy-in-batches).

**Comment by jobasque** [comment]
Verified unique Function Apps may be created per host pool
