### ISSUE TITLE
Include the option to also remove the Intune object

### ISSUE THREAD

**Issue by jpplaisier** [Azure/AVDSessionHostReplacer#9]
Currently our Entra ID joined, Intune managed AVD session hosts are cleaned up only in Entra ID. I also would like to have an option to also delete the object in Intune.

**Comment by joshbasquez** [comment]
https://github.com/Azure/AVDSessionHostReplacer/pull/11

Added fix, Submitted pull request above to Willy.

**Comment by WillyMoselhy** [comment]
In my testing I only needed to clean the object in Entra ID, and creating a new device with same name works. Why do we need to delete it in Intune?

**Comment by jpplaisier** [comment]
Strange, because in my Intune tenant I see lots of duplicate device records in Intune

**Comment by WillyMoselhy** [comment]
Added in [v.0.2.8](https://github.com/Azure/AVDSessionHostReplacer/releases/tag/v0.2.8)
